export const constants = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_PRODUCTS_LIST: "SET_PRODUCTS_LIST",
    SET_PRODUCTS_POST :"SET_PRODUCTS_POST",
    SET_PRODUCTS_DELETE :"SET_PRODUCTS_DELETE",
    SET_PRODUCTS_PUT :"SET_PRODUCTS_PUT",
  };
